### ISSUE TITLE
Add File Blacklist Feature

### ISSUE THREAD

**Issue by brandonio21** [brandonio21/download-sweeper#13]
As issue #8 revealed, there is need for a "file blacklist" feature, where the user specifies a list of files/directories that should not be touched by download-sweeper.

The blacklist can be added to `config.yaml`. A blacklisted file should never be moved, while a blacklisted folder should never be moved and its contents never explored.

**Comment by prkumar** [comment]
What do you think about adding support for Unix-style wildcards?

**Comment by brandonio21** [comment]
@prkumar Sounds like a solid ask to me.

**Comment by brandonio21** [comment]
@prkumar  Added in 8a42885c924873d26e08b2a56ea8cd78fa82c228
